name: Zonaprop Checker

on:
  schedule:
    - cron: '0 * * * *'   # every hour at minute 0
  workflow_dispatch:       # manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          playwright install chromium

      - name: Run script
        run: python zonaprop_check.py
